name: Deploy to gh-pages

on:
  push:
    branches:
      - master

jobs:
  deploy_and_create_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy using DEPLOY_TOKEN
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          #personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./public
        if: secrets.DEPLOY_TOKEN

      - name: Deploy using GITHUB_TOKEN
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
        if: secrets.GITHUB_TOKEN && !secrets.DEPLOY_TOKEN
